// Custom shader file for void4.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

void4/10A7511046AB81DBAC3E2C1EDB80F1AE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/snoise2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/60C133936D6E17A2F1F782FCFEB8BEA6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_stuff2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/8B6AE6D4FB9F6D78DBC09AB872BCE276
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/+0squarea.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/0553971A655E3F9B309579CB533F0CC9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/spipe2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/DBF43D7CEFEDE9E1C21AC599E4FE6469
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_side5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/F15ADB9B70ED692F842EA17D15FAF4F5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_stuff2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/6ADCDDEA4FAA072989C562D02FFDD7FA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/snoise2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/37ED4D4F8BD0BCB45BFDF0A4165B5F9E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/snoise2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/ACE3B87BEEC1E34B35715BC91AE3D7FD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_tower1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/F82BF9027AB93276E2651808FE851B64
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_tower1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/9BC8EFD33ABE3692BB738B2CA3D8BEE3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_side5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/4450D877FACC779D8C08C2768A6EB813
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_side5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/35ADD234EEAEA2AF489D72E5E5E50FE6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_tower1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/4F6E88C4BFDAF1F49F9EB4B21E59DA05
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_side5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/D6C8C6F3322BA114A8E853D0225ECC92
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_tower1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/0C53C3C1E1BECBA5FBA20FFE03BD9C00
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_top3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void4/EF2C9F9CC692CBE00C025A48E831A95B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void4/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/baloneydoor2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

