// Custom shader file for void3.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

void3/5D651BEB44272145316FE544895BE00B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/hazard_crate.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/9D46DF6067296591B09428FBD8312C95
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_crate2top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/8878EC2E8A8DB61A1316C33D15D42890
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/brownwirewall.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/488E03A7E77C97A752D1FF794FCF4B3B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/slight2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/D65DF5AF8CCB19CC34ED5CE2F0A88E8A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_top4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/833AEEDB708C78F9D7E311567EAEE33E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/oquartz/u_tex23b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/A81A0F1090B37B3AC3C84EF2F722C856
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/sbrick1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/3A6A8899C9D574FC5F78EB82610748F7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/ulrich4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/288A820BEF41BEFAAB9B175B8BA82146
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/u_tex23.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/760442B2BF0AD6E1B27F71B088D781FA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/ulrich4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/99FE595D7254E6D96A460D034509D167
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/s128r.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/B73C6A23EFC5E52B467DFA085A9062EF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/nolight.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/FF9F753B97D56A50DAE476697406A5F8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/nolight.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/613936FFC48392CE640D37136FDA110A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_light1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/BA0FFCBFED860C98D8C980C5F1D76242
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_crate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/4FAD5573FD9C0B334C4497A875693548
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_crate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/9F8C0ED2995195143E459961D4B14E24
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/u_tex23b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/CA30CEE552ABEB2DC477BEF252FE8219
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/sbrick2b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/0580BA8F6E49F04C603736414F2D2D3D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/u_tex23.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/8627078676A4ED36C83F3DB6C37DB596
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/sbrick2b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/9A721BD1257F9DAB35215E3BEE91D82A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/slight2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/A536628F978B5E50C483A988FC3EB935
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/ulrich4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/056F2A2B87C0719DBEC79C5E51CC64D2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/u_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/96245F482B34CD596EA1513BAC562CE6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/u_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/4D2BCD94282B04529D5FFC00F99B7956
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/u_tex23b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/DDCC5B6EB89841DBE4380BE99934B099
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_side7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/34375FF2A4E1D5CDB1241ED690684DCD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/flatgray.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/65FF7FECEF595FD7CD23FF90A4849308
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/stlight2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/0DD4069161C8AC44961108F4051AC7CC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/flatgray.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/6E51518A8FC921D0C6A995EDEA615BFD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/clip.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/71786F69997DB563EF231F6F19CEBDBF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/shex2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/64825ADF0823B97FA170FDC9A96098F2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/cor5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/3032DC7E2B74CE2EA3810112C327D273
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_thing1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/DFE25D4E0ECBF9DE597EA73E0D050D13
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/+0squarea.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/3DF1D8C057B3FFC61F44F76375AE510D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/s128t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/E91DFAE050744E2638B7D0EE491AD47E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/black.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/E40C347F377F4C7B4418AD093AC85B41
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}

	{
		map textures/oquartz/ulrich24.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/64BDF1F44E33450F6E2F7771BC0CDE97
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/ulrich21.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/49EF8054B49AE8B8EB455D0257EEB7DD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/s128r.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/EAB2F8E3C05A78369ADA36D7AB9CECF9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/sbrick2b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/BFA4F53C9802AE4F07D4D89A0B5A7D78
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/snoise3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/2429852938D133BC2F87AE30EF23F5C8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_top3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/9F1984C0C99F78807CD400F229EB204D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/tsl_bottom3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/77C3CA25ADF14E44CF1FE3A5720C05A4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/cor6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

void3/F46B87647D3591F59C656A576C28E01C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/void3/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 10
		tcGen lightmap
	}

	{
		map textures/oquartz/+aulrichbut.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

