// Custom shader file for q3r_nightcity.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

q3r_nightcity/A667E64F357C083D18212681D5ADDACD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/007D4EB39F8199C4BAA7B633D858CD15
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C7A913029C27B3531AACD62E16E4D6C1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/1FC81F4D45E16015AB82350188B96415
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/1A3C68B88548B56DB8603CF19DF0959F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/base_light/jaildr1_3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/A642A385FD0BE52B088C635779E05982
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C7403AB2DBFA8FCB5DC83A50B4546186
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/5B9099CE42E521B6C7E16C0D79E27448
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/8F0BD2A69D3147D635809C467838C6C1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C16660C4B5CF25EA20D2EC999F2147FB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/base_light/light5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/641395F602219BE7DDCDAF6FCBBC434A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/DABA5EE8BEE044B1600CE8636B6E8E61
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/F35578726B0AE940585908C59FCD0A54
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/6C384E2C484B46A124B2D9A7B63F8A08
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/13ADD7D031DC53E81368610AAAA5B17C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.42188 0.00000
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/445835F8AD812A28BDF9E20FCCB06931
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.01563 0.01563
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/816E7B01698D8429B4AAD4431F2BD20F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/DEEEB8E9A89F3D207DA2213FCF8F120B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/B98C441753555352684072022814A207
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/B67049EF56A4B71CDBA930C8661C1D6F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.04688 0.07813
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/DF1FF650D6CE9CCF30B6269C947A2A08
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C8A9B640A83B5392DF487EAB6DF1E5C4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/307CDE25F299A7D99C0C530147ADA02B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/731528C33819EA8257BBD5E9EADCD1A4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.44531 0.03906
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C4181AA87714023C44450303D1D775CA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.18750 -0.35938
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/036F404341A17C57832F6956E519ED0A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.12500 0.11719
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/508FFCA1FBAC3A68BDB09BD29EB6A509
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/A3EE92C6FC68BFE7F6F3B9DB00A4BB66
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/4DD84EE62C42CF664C86B4A5C05BC918
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/DCE74BC70FFB92D33F9382198EA7862B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/7B1E6AF2306A190B5C4BCFC92592D0EA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.13281 0.06250
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/F588905C381637AAD0E5C73F3A4D2C32
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/B1297C047F63E3423F30C5A36220875F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_building/windows8.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/969532CBE5255E6D46BFF500FFF73356
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/478F5744F149554441B26E0A6457E41D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/FAD1CB51FC14AE3A172423922A4B8A82
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/CF26B03DD4D9FB5FF86A3088B173B71D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/0F10FCB0368087EDD569CECEBBDD17DD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/81A3D0EF94713D0BB1AFD70025C58190
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/0A1BCED38EFE8050E3EB684EEB3C08AE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/EA4C70BC86E93CBF94726E8DCC3A2345
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.89844 0.01563
	}

	{
		map textures/base_trim/tin.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/658FC9E6E009AEB98AF7A71823D75ABF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/base_trim/tin.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/50E8BA9CC309E44788D3BF8E2ABFFE85
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/base_wall/bluemetal3b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/76471E9E4213855213318174D7AB9831
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.89844 0.01563
	}

	{
		map textures/base_wall/bluemetal3b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/CF5A5FEA51A778FF10B6C4649B52A519
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/base_wall/bluemetal3b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/1A16E1724451A5F4F37C841233753C90
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/sfx/beam.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/DFC14CD9027DCBB44DC98767D3C709A3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/AF781ACB2DA6BAD2AA8FABD46B836AD6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.26563 -0.38281
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/8ED79E978207ED1A3EB99160C7812344
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/7BB03FC9F06A2AA2AF5CD98EF7300FD7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/4F765AC207CE3C10FE15980150CF3194
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/7629E617423CC5AC3D9B508BC8A3566F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/4E6B34CAED37319ABF0128F1099BEFA8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/D78262BBBF3100C4B219BED983829505
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/EAC0504AD179FB5D12DA6BD172F2AD91
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/9D47BDD21716EA3536F0EF8AD4C70FD5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/0E5289E7706FE6BD7A876B1DFC5B5300
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/A4786242D252798DB9A26868AD78FC54
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/4CB4D0CD0896DFDDF88DF9B42D6E6788
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/1CF514C79DF3EBF941AE902D808B8D80
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/49E7A3A96A2384CFE9B3163F6E005E8A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/1E03FFBF155F169E016F8559F3D7EBBA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C71F806BE5915C1D42AFB9E3A9BFB4D6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.02344
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C563B4078CF228CE90FB511377F615B6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/58FBFBA63CBDB2D3ACFC3940AEC1D69F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.33594 0.16406
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/FE2195A904B6D08572223047F7EBCA17
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.96875 0.00000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/4E65A2CDE03B7F9693450D640F9B5A28
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/F61C043E7026C34E04EC4949EBB6D837
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.32031 0.21094
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/F745124B0266D9E64C6AE18302F65DC8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/5E6FD315416603FCC61A825B592D98E3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/8A9CA2E5BF8D3EB775F0C3A6836009F3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/AEBAB75166F2CD28AF69ACB56045ADF0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.54688 0.07813
	}

	{
		map textures/q3r_road/asphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/8B3F26E3CD257910E18A0311DD693CEA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/B3E4B2306CCCF3DE7DFFE9EE973E4D31
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/A586E109648898AAF52C6DED3010AECC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/NULL.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/6C37767646C0C9A32F3EF48F8CDC4822
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/CEEAC0458312047DA0910F7C67299C83
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/0038EB9B4CF7EE941C72FAAF927E37FA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/ADCAFFDAE6D61652E44D4D2147BE566F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_metals/cormetal04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/C029A0346A8B1F5486C3D1ACDBD1411A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_dirt_grass/checker01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/EDAA92ED44F48D8F2732A8C2AB509ED9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/base_trim/tin.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/46A22FF98F656932C3168A837AB123FD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/base_wall/bluemetal3b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/1C8A8018C6D399C918DB5F4FC44CDFB4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/sfx/beam.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/0E65BEF49065B9CDE11192526FA83B3D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/sfx/beam.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/E41AEC5BF0AE0A10A89D468407B79597
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/6232F081DBE6202D5A8102D99BAA14D1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/0557049EA85E6E59B7F68154D480F1ED
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03906 0.00000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/D1E13E2198E7996C38ABD2CBE218A84D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/1D869F4FEB047A7C88C0135315B6BF6D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

q3r_nightcity/09B65598E4B67E641E4994C8AB635C28
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3r_nightcity/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 5
		tcGen lightmap
	}

	{
		map textures/q3r_road/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

